#!/usr/bin/env bash

BASE_URL="http://1tv.ru/news/issue"
DATE_BIN=date

if ! which yt-dlp 1>/dev/null; then
    echo Error: yt-dlp not found
    exit -1
fi
if [[ $(uname -s) == Darwin ]]; then
    if ! which gdate 1>/dev/null; then
        echo Error: gdate not found
        exit -1
    else
        DATE_BIN=gdate
    fi
fi

DATE=$($DATE_BIN --date='yesterday' +%Y-%m-%d)
DOWNLOADS="./downloads"
URL="${BASE_URL}/${DATE}/21:00"
OUT="${DOWNLOADS}/vremya_${DATE}.mp4"

yt-dlp ${URL} -o ${OUT}
