#!/usr/bin/env bash

# Simple solution for switch alacritty terminal font size (when work with
# or without glasses)

CONFIG=~/.alacritty.yml
CURRENT=$(grep "^  size:" ${CONFIG}|cut -d ":" -f 2|cut -d " " -f 2)
NORMAL=12.5

if [ "$1" == "-B" ]; then
    GLASSES_OFF=29.5
else
    GLASSES_OFF=17
fi

if [ $CURRENT == $NORMAL ]; then
    NEW_SIZE=$GLASSES_OFF
else
    NEW_SIZE=$NORMAL
fi

# TODO testing in Linux environment
sed "s/  size: .*/  size: ${NEW_SIZE}/" ${CONFIG} > ${CONFIG}.new \
    && (cat ${CONFIG}.new > ${CONFIG}; rm ${CONFIG}.new)
