#!/usr/bin/env bash

# Toggle font size in alacritty terminal when work with (or without) glasses

CONFIG=~/.alacritty.yml
CURRENT=$(grep "^  size:" ${CONFIG}|cut -d ":" -f 2|cut -d " " -f 2)
NORMAL=17.0
GLASSES_OFF=26.5

if [ $CURRENT == $NORMAL ]; then
    NEW_SIZE=$GLASSES_OFF
else
    NEW_SIZE=$NORMAL
fi

sed -i "" -e "s/  size: .*/  size: ${NEW_SIZE}/" ${CONFIG} # tested at macos
