#!/bin/bash

#magnet:?xt=urn:btih:8B5C7A9988E4CFEFF51D922AFDAC4BCF8AFFA832&tr=http%3A%2F%2Fbt4.t-ru.org%2Fann%3Fmagnet&dn=%D0%94%D0%B6%D0%B5%D0%BA%20%D0%A0%D0%B8%D1%87%D0%B5%D1%80%20%2F%20Jack%20Reacher%20(%D0%9A%D1%80%D0%B8%D1%81%D1%82%D0%BE%D1%84%D0%B5%D1%80%20%D0%9C%D0%B0%D0%BA%D0%9A%D1%83%D0%BE%D1%80%D1%80%D0%B8%20%2F%20Christopher%20McQuarrie)%20%5B2012%2C%20%D0%A1%D0%A8%D0%90%2C%20%D0%91%D0%BE%D0%B5%D0%B2%D0%B8%D0%BA%2C%20%D1%82%D1%80%D0%B8%D0%BB%D0%BB%D0%B5%D1%80%2C%20%D0%BA%D1%80%D0%B8%D0%BC%D0%B8%D0%BD%D0%B0%D0%BB%2C%20%D0%B4%D0%B5%D1%82%D0%B5%D0%BA%D1%82%D0%B8%D0%B2%2C%20BDRip%201080p%5D%20Dub%20%2B%205x%20AVO%20%2B%20S
if [ $# != 1 ]; then
    echo "Usage: $0 <magnet URL>"
    exit -1
fi
STR="$1"
export HASH=$(echo -n $STR \
    | cut -d "&" -f 1 \
    | rev | cut -d ":" -f 1 | rev)
export CMD="uname -r $1"
st -i -g 100x12+4400+400 -e bash -c '
input=$(dialog \
    --erase-on-exit \
    --inputbox "Exec? " -1 -1 "$CMD" \
    3>&1 1>&2 2>&3 3>&-)
echo "$input"
read -r'
#TASK_ID=$(task add test \
#    | grep "Created task" | rev | cut -d " " -f 1 | rev | cut -d "." -f1)
# # TODO check for $TASK_ID is number
#echo $TASK_ID was added
#task $TASK_ID ann "ann test 0"
