#!/bin/bash

if ! which xclip &>/dev/null; then
    echo "Error: xclip is not found"
    exit -1
fi
if [ $# != 1 ]; then
    echo "Usage: $0 <magnet URL>"
    exit -1
fi
STR="$1"
export HASH=$(echo -n $STR \
    | cut -d "&" -f 1 \
    | rev | cut -d ":" -f 1 | rev)
export NAME=$(echo -n $STR \
    | rev | cut -d "&" -f 1 | rev \
    | cut -d "=" -f 2 \
    | sed "s@+@ @g;s@%@\\\\x@g" | xargs -0 printf "%b")
export CMD="task add +film \"$NAME (1h30min)\""
echo -n $HASH | xclip
st -i -g 100x12+4400+400 -e bash -c '
NAME_EDITED=$(dialog \
    --erase-on-exit \
    --inputbox "Exec? " -1 -1 "$CMD" \
    3>&1 1>&2 2>&3 3>&-)
if [ "x$NAME_EDITED" == "x" ]; then
    exit
fi
TASK_ID=$($NAME_EDITED \
    | grep "Created task" | rev | cut -d " " -f 1 | rev | cut -d "." -f1)
task $TASK_ID ann "$HASH"'
