#!/usr/bin/env bash

MIN_COLUMNS_SIZE=96
MID_COLUMNS_SIZE=144
MIN_TASK_SIZE=24
MID_TASK_SIZE=40
IS_TASK_ACTIVE=false

COLUMNS=$1

if task +ACTIVE all &>/dev/null; then
    IS_TASK_ACTIVE=true
fi

if (( $COLUMNS <= $MIN_COLUMNS_SIZE )) && ! $IS_TASK_ACTIVE; then
    tmux_mpc $MID_COLUMNS_SIZE
elif (( $COLUMNS > $MIN_COLUMNS_SIZE )) && $IS_TASK_ACTIVE; then
    tmux_task $COLUMNS
    tmux_mpc $MID_COLUMNS_SIZE
else
    tmux_task $COLUMNS
    tmux_mpc $COLUMNS
fi
