#!/usr/bin/env bash

export TIMEWARRIORDB=$HOME/.timewarrior_officetime

DAY=$(timew :day worktime)
WEEK=$(WORKTIME_FORMAT=hour timew :week worktime)
MONTH=$(WORKTIME_FORMAT=hour timew :month worktime)

echo -n "[${DAY}/${WEEK}/${MONTH}]"
